version: '3.4'

services:
  lr1.api:
      environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      ports:
      - "8000:8080"
  lr1.client:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - TextProcessingServiceUri=http://lr1.api:8080
    ports:
      - "8001:8080"
    depends_on:
      - lr1.api
