version: '3.4'

services:
  lr1.api:
    image: ${DOCKER_REGISTRY-}lr1api
    build:
      context: .
      dockerfile: LR1.API/Dockerfile
  lr1.client:
    image: ${DOCKER_REGISTRY-}lr1client
    build:
      context: .
      dockerfile: LR1.Client/Dockerfile
